if (Teams.find().count() === 0) {
  Teams.insert({number: 1, name: '', nameLocked: false, guesses: [{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false}]});
  Teams.insert({number: 2, name: '', nameLocked: false, guesses: [{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false}]});
  Teams.insert({number: 3, name: '', nameLocked: false, guesses: [{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false}]});
  Teams.insert({number: 4, name: '', nameLocked: false, guesses: [{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false}]});
  Teams.insert({number: 5, name: '', nameLocked: false, guesses: [{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false}]});
  Teams.insert({number: 6, name: '', nameLocked: false, guesses: [{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false}]});
  Teams.insert({number: 7, name: '', nameLocked: false, guesses: [{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false}]});
  Teams.insert({number: 8, name: '', nameLocked: false, guesses: [{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false},{guess: '', guessLocked: false}]});
};